"""Add cost, attachments, and general maintenance

Revision ID: 799d36de7b57
Revises: 
Create Date: 2025-11-28 14:29:09.530149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799d36de7b57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
